name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: projetos_laravel_test
          MYSQL_USER: laisa
          MYSQL_PASSWORD: laisa1234
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: projetos_laravel_test
      DB_USERNAME: laisa
      DB_PASSWORD: laisa1234
      APP_ENV: testing
      APP_DEBUG: true

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar PHP e extensões
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, mysql
          coverage: none

      - name: Instalar dependências do Laravel
        run: composer install --no-progress --prefer-dist
        working-directory: ./app

      - name: Copiar .env.testing para .env
        run: cp .env.testing .env
        working-directory: ./app

      - name: Gerar chave da aplicação
        run: php artisan key:generate
        working-directory: ./app

      - name: Aguardar MySQL ficar pronto
        run: |
          for i in {1..10}; do
            mysqladmin ping -h 127.0.0.1 --silent && break
            echo "Esperando MySQL..."
            sleep 5
          done

      - name: Rodar migrations
        run: php artisan migrate --force
        working-directory: ./app
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: projetos_laravel_test
          DB_USERNAME: laisa
          DB_PASSWORD: laisa1234

      - name: Rodar testes
        run: php artisan test
        working-directory: ./app
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: projetos_laravel_test
          DB_USERNAME: laisa
          DB_PASSWORD: laisa1234
